# fly.toml app configuration file generated for misty-leaf-9664 on 2023-06-24T01:14:39-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "misty-leaf-9664"
primary_region = "sea"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
